version: '3.8'
services:
    postgres:
        container_name: container-pg
        image: postgres:10.5
        hostname: localhost
        restart: always
        environment: 
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
        ports:
          - '5438:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create agent table
          - ./sql/create_agent_table.sql:/docker-entrypoint-initdb.d/create_agent_table.sql